Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="193" judge-id="3" status="SE" scoring="ACM" run-tests="1" contest-id="3103" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>8eb61a8a-cdbc-4f0a-ba59-d606a34fa5ba</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="283" real-time="319" max-memory-used="32251904" >
  <program-stats-str>{ utime=274, stime=9, ptime=283, rtime=319, maxvsz=32251904, maxrss=19144704, nvcsw=2, nivcsw=35 }</program-stats-str>
      <input size="16">4 3
1 2
2 3
1 3
</input>
      <output size="0"></output>
      <stderr size="490">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000193&quot;, line 28, in &lt;module&gt;
    dfs(i, 1)
  File &quot;./000193&quot;, line 21, in dfs
    dfs(u, 3 - c)
  File &quot;./000193&quot;, line 21, in dfs
    dfs(u, 3 - c)
  File &quot;./000193&quot;, line 21, in dfs
    dfs(u, 3 - c)
  File &quot;./000193&quot;, line 19, in dfs
    for u in ar[v]:
IndexError: list index out of range
</stderr>
    </test>
  </tests>
</testing-report>
